site_name: DevOps and Developer Productivity
repo_url: https://github.com/varsharaju/product-doc-sample
edit_uri: edit/master/docs/

nav:
  - Solutions:
    - CICD: product/cicd.md
  - Partners: partners.md
  - Customers: casestudies.md
  - Training: training/presentations.md
  - Support: support/help.md

theme:
  name: simplex
  #custom_dir: theme

markdown_extensions:
  - codehilite
  - admonition
